### ISSUE TITLE
新组件注册机制报错

### ISSUE THREAD

**Issue by wsz1234567** [SXQ-STUDY/BSSNet#3]
首先，谢谢你的分享。然后我在运行的时候遇到了如下的报错：KeyError: 'BSSNet_T is not in the mmseg::model registry. Please check whether the value of `BSSNet_T` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
应该如何解决呢？谢谢了

**Comment by XiaoQiangSHI** [comment]
1. Ensure that you have configured the environment according to the mmsegmentation official documentation. 
2. Clone this code repository.
3. pip install -v -e .

**Comment by wsz1234567** [comment]
OK,it works,Thank you!
