### ISSUE TITLE
Can you provide an imagenet pre-trained model of the network?

### ISSUE THREAD

**Issue by AAAdecade** [SXQ-STUDY/BSSNet#8]
hello

Thank you for your outstanding work

Can you provide an imagenet pre-trained model of the network?

**Comment by XiaoQiangSHI** [comment]
The pre-training weights are PIDNet.

**Comment by AAAdecade** [comment]
> The pre-training weights are PIDNet.

Thank you for your reply, which of the S, M, and L of PIDNet is it? thanks for your help！
![image](https://github.com/SXQ-STUDY/BSSNet/assets/145337236/d964129d-bcd6-4a64-956f-d850a68be838)
